name: Api call

on:
  workflow_call:
    secrets:
      server:
        required: true
      oauth:
        required: true
      method:
        required: true
      api:
        required: true
      data:
        required: true
jobs:
  api_call:
    runs-on: ubuntu-latest
    steps:
      - name: Api call
        run: |
          req_oauth=${{ format('{0}{1}', secrets.server, secrets.oauth) }}
          echo $req_oauth
          resp_oauth=$(curl -s -w "\n%{http_code}" $req_oauth)
          resp_oauth=(${resp_oauth[@]})
          http_code=${resp_oauth[-1]}
          if [ $http_code -ne 200 ]; then
            echo "Authentication failed"
            exit 1
          fi
          token=$(echo ${resp_oauth[0]} | jq '.token' | cut -d '"' -f2)
          req_api=${{ format('{0}{1}', secrets.server, secrets.api) }}
          resp_api=$(curl -m 120 -s -w "\n%{http_code}" --request ${{secrets.method}} $req_api --header 'Content-Type: application/json' --header 'Authorization: $token' --data-raw '${{secrets.data}}')
          echo $resp_api
          resp_api=(${resp_api[@]})
          json=${resp_api[@]::${#resp_api[@]}-1}
          output=$(echo $json | jq '.output' )
          echo -e $output
          api_code=${resp_api[-1]}
          if [$api_code -ne 200 ]; then
            echo "Error calling api
            exit 1
          fi
          
          
         
          
          
          
            
          
          
          
          
