name: deploy

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      chart_folder:
        required: false
        type: string
        default: chart
      cluster_name:
        required: true
        type: string
      cluster_role_arn:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      values:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        uses: craftech-io/eks-helm-deploy-action@v1 # https://github.com/craftech-io/eks-helm-deploy-action
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1
          cluster-name: ${{ inputs.cluster_name }}
          cluster-role-arn: ${{ inputs.cluster_role_arn }}
          chart-path: ${{ inputs.chart_folder }}/
          values: ${{ secrets.values }}
          namespace: ${{ inputs.repo_name }}
          name: ${{ inputs.repo_name }}
