name: deploy

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      chart_folder:
        required: true
        type: string
      dns:
        required: true
        type: string
      cluster_name:
        required: true
        type: string    
      cluster_role_arn:
        required: true
        type: string        
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true        
      db_host:
        required: true
      db_user:
        required: true
      db_password:
        required: true
      email_user:
        required: true
      email_password:
        required: true
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ inputs.repo_name }}
      DNS: ${{ inputs.dns }}      
      DB_HOST: ${{ secrets.db_host }}
      DB_USER: ${{ secrets.db_user }}
      DB_PASS: ${{ secrets.db_password }}
      EMAIL_USER: ${{ secrets.email_user }}
      EMAIL_PASS: ${{ secrets.email_password }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        uses: craftech-io/eks-helm-deploy-action@v1 # https://github.com/craftech-io/eks-helm-deploy-action
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: us-east-1
          cluster-name: ${{ inputs.cluster_name }}
          cluster-role-arn: ${{ inputs.cluster_role_arn }}
          chart-path: ${{ inputs.chart_folder }}/
          values: build=${{ github.run_number }},dns=${{ env.DNS }},db.host=${{ env.DB_HOST }},db.user=${{ env.DB_USER }},db.password=${{ env.DB_PASS }},email.user=${{ env.EMAIL_USER }},email.password=${{ env.EMAIL_PASS }}
          namespace: ${{ env.REPO_NAME }}
          name: ${{ env.REPO_NAME }}
