name: Notifify Crucible

on:
  workflow_call:
    inputs:
      repo_key:
        required: true
        type: string
      crucible_host:
        required: false
        type: string
    secrets:
      api_key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update crucible repo index
        run: |
          curl --location --request PUT '${{ inputs.crucible_host }}/rest-service-fecru/admin/repositories/${{ inputs.repo_key }}/incremental-index' --header 'x-api-key: ${{ secrets.api_key }}'
          
     
