name: Notifify Crucible

on:
  workflow_call:
    inputs:
      port:
        required: false
        type: string
        default: 443
      repo_key:
        required: true
        type: string
      crucible_host:
        required: false
        type: string
    secrets:
      api_key:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_default_region:
        required: false
      security_group_id:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get public IP
        if: ${{ !contains( github.ref , 'dependabot') }}
        id: ip
        run: |
          PUBLIC_IP=$(curl -sS https://api.ipify.org) || true
          if [[ -z "$PUBLIC_IP" ]]; then
            echo "Service 1 failed. Trying Service 2..."
            PUBLIC_IP=$(curl -sS ifconfig.co/ip)
          fi
          echo "IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Update security group ingress
        if: ${{ !contains( github.ref , 'dependabot') }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
        run: |
          securityGroupIds=${{ secrets.security_group_id }}
          ruleDescription=GitHubActions-port-${{ inputs.port }}
          rulePort=${{ inputs.port }}
          publicIP=${{ env.IP }}
          securityGroupRuleId=$(aws ec2 describe-security-group-rules --filter Name="group-id",Values="'$securityGroupIds'" | jq -r '.SecurityGroupRules[0] | select(.CidrIpv4 == "'$publicIP/32'") | .SecurityGroupRuleId')
          if [ -z "${securityGroupRuleId}" ]; then
              aws ec2 authorize-security-group-ingress --group-id $securityGroupIds --ip-permissions '[{"IpProtocol": "tcp", "FromPort": '$rulePort', "ToPort": '$rulePort', "IpRanges": [{"CidrIp": "'$publicIP/32'", "Description": "'$ruleDescription'"}]}]'
          fi

      - name: Update crucible repo index
        run: |
          curl --location --request PUT '${{ inputs.crucible_host }}/rest-service-fecru/admin/repositories/${{ inputs.repo_key }}/incremental-index' --header 'x-api-key: ${{ secrets.api_key }}'
          
     
