name: Sync github repo

on:
  workflow_call:
    inputs:
      origin_repo_name:
        required: true
        type: string
      dest_repo_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string
    secrets:
      origin_repo_key_id:
        required: true
      dest_repo_key_id:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: git-sync
        run: |
          git remote add upstream https://${{ secrets.dest_repo_key_id }}@github.com/${{ inputs.dest_repo_name }}
          git push upstream ${{ inputs.branch_name }}
